config/routes.rb
Trenum::Application.routes.draw do
  resources :documents do
    member do
      put "/cancelar" => "documents#cancel", :as => "cancel"
    end
  end

  
  

end

app/models/document.rb
# == Schema Information
#
# Table name: documents
#
#  id              :integer         not null, primary key
#  user_id         :integer
#  doctype         :string(255)
#  subject         :string(255)
#  recipient       :string(255)
#  dispatch_number :integer
#  created_at      :datetime
#  updated_at      :datetime
#  status          :string(255)
#  pdf_file        :string(255)
#

class Document < ActiveRecord::Base
  belongs_to :user
  mount_uploader :pdf_file, PdfFileUploader
  validates :doctype, :subject, :recipient, :presence => true
  validates_uniqueness_of :dispatch_number, :scope => :doctype
  attr_accessible :user_id, :doctype, :subject, :recipient, :dispatch_number, :status, :pdf_file
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer         not null, primary key
#  email                  :string(255)     default(""), not null
#  encrypted_password     :string(128)     default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer         default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  failed_attempts        :integer         default(0)
#  unlock_token           :string(255)
#  locked_at              :datetime
#  created_at             :datetime
#  updated_at             :datetime
#  admin                  :boolean         default(FALSE)
#  name                   :string(255)
#  workplace              :string(255)
#

class User < ActiveRecord::Base
  has_many :documents
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable and :omniauthable
  #devise :database_authenticatable, :registerable, :confirmable, :lockable,
  #       :recoverable, :rememberable, :trackable, :validatable, :timeoutable
  # Só emails do TRE-SP
  email_regex = /^([^@\s]+)@(tre-sp.gov.br||wm.tre-sp.gov.br)$/i
  # Qualquer email
  # email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, :format => { :with => email_regex }
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :workplace, :admin
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def self.current_user
    session['current_user']
  end
  
  def after_sign_in_path_for(resource)
  	# for monodocument phase :)
  	documents_path
  end

  def check_profile_completeness
    redirect_to login_path if current_user.name.nil? || current_user.workplace.nil?
  end
end

app/controllers/documents_controller.rb
#encoding:UTF-8
class DocumentsController < ApplicationController
  before_filter :check_profile_completeness
  
  def index
    unless current_user.admin?
      @documents = current_user.documents.order('doctype asc')
    else
      @documents = Document.all
    end
  end

  def show
    @document = Document.find(params[:id])
  end

  def new
    @document = Document.new
  end

  def create
    @document = current_user.documents.build(params[:document])
    @document_by_type = Document.find_all_by_doctype(@document.doctype)
    unless @document_by_type.empty?
      @document.update_attributes(:dispatch_number => Document.order('dispatch_number asc').find_all_by_doctype(@document.doctype).last.dispatch_number + 1, :status => "Upload pendente")
    else
      @document.update_attributes(:dispatch_number => 1, :status => "Upload pendente")
    end
    if @document.save
      redirect_to documents_path, :notice => "Número gerado com sucesso: <span class=\"big-number\">#{@document.dispatch_number}</span><br />Por favor, não se esqueça de fazer o upload de uma cópia do documento assinado após o envio.".html_safe
    else
      render :action => 'new'
    end
  end

  def edit
    @document = Document.find(params[:id])
  end

  def update
    @document = Document.find(params[:id])
    if @document.update_attributes(params[:document])
      if !@document.pdf_file.blank? && @document.status != "Finalizado"
        @document.update_attributes(:status => "Finalizado")
        redirect_to documents_path, :notice  => "Documento finalizado com sucesso. Obrigado!"
      else
        redirect_to @document, :notice  => "Documento atualizado com sucesso."
      end
    else
      render :action => 'edit'
    end
  end

  def destroy
    @document = Document.find(params[:id])
    @document.destroy
    redirect_to documents_url, :notice => "Documento destruído com sucesso."
  end

  def cancel
    @document = Document.find(params[:id])
    @document.update_attributes(:status => "Cancelado")
    if @document.update_attributes(params[:document])
      redirect_to @document, :notice => "Documento cancelado com sucesso"
    else
      render :action => 'show'
      flash.now[:error] = "Seu documento não foi cancelado. Por favor tente novamente."
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/error_messages_helper.rb
#encoding:UTF-8
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Campos inválidos")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Corrija os seguintes erros e tente novamente.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = false)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/documents/_form.html.erb
<%= form_for @document do |f| %>
  <%= f.error_messages %>
  <p>
    Usuário: <strong><%= current_user.name %></strong>
  </p>
  <p>
    Unidade: <strong><%= current_user.workplace %></strong>
  </p>
  <p>
    Tipo: <%= f.select :doctype, ["Ofício", "Portaria", "Resolução"] %>
  </p>
  <p>
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </p>
  <p>
    <%= f.label :recipient %><br />
    <%= f.text_field :recipient %>
  </p>
  <p><%= f.submit "Gerar número", :confirm => "Por favor confira se os dados estão corretos." %></p>
<% end %>

app/views/documents/edit.html.erb
<% title "Editar Documento" %>

<%= render 'form' %>

<p>
  <%= link_to "Ver", @document %> |
  <%= link_to "Ver todos", documents_path %>
</p>

app/views/documents/index.html.erb
<% title "Documentos" %>

<table>
  <tr>
    <th>Tipo</th>
    <th>Assunto</th>
    <th>Destinatário</th>
    <th>Número</th>
    <th>Status</th>
    <th>Arquivo</th>
  </tr>
  <% for document in @documents %>
    <tr>
      <td><%= document.doctype %></td>
      <td><%= document.subject %></td>
      <td><%= document.recipient %></td>
      <td style="text-align:right"><%= document.dispatch_number %></td>
      <% if document.status == "Upload pendente" %>
        <td style="color:red;font-weight:bold"><%= document.status %></td>
      <% else %>
        <td><%= document.status %></td>
      <% end %>
      <td>
      <% unless document.pdf_file.blank? %>
        <%= link_to "Baixar", document.pdf_file.url %>
      <% end %>
      </td>
      <td><%= link_to "Ver", document, :class => "note" %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "Gerar número", new_document_path %></p>

app/views/documents/new.html.erb
<% title "Novo Documento" %>

<%= render 'form' %>

<p><%= link_to "Voltar à lista", documents_path %></p>

app/views/documents/show.html.erb
<% title "#{@document.doctype} n. #{@document.dispatch_number}" %>

<p>
  <strong>Usuário:</strong>
  <%= @document.user.name %>
</p>
<p>
  <strong>Unidade:</strong>
  <%= @document.user.workplace %>
</p>
<p>
  <strong>Tipo:</strong>
  <%= @document.doctype %>
</p>
<p>
  <strong>Número:</strong>
  <%= @document.dispatch_number %>
</p>
<p>
  <strong>Assunto:</strong>
  <%= @document.subject %>
</p>
<p>
  <strong>Destinatário:</strong>
  <%= @document.recipient %>
</p>
<p>
  <strong>Status:</strong>
  <%= @document.status %>
</p>
<% if @document.pdf_file.blank? && @document.status == "Upload pendente" %>
  <%= form_for @document, :html => {:multipart => true} do |f| %>
    <%= f.error_messages %>
    <%= f.file_field :pdf_file %><br />
    <%= f.submit "Enviar documento" %>
  <% end %>
<% end %>
<p>
  <% if current_user.admin? %>
    <%= link_to "Editar", edit_document_path(@document) %> |
    <%= link_to "Destruir", @document, :confirm => 'Você tem certeza?', :method => :delete %> |
  <% end %>
  <%= link_to "Cancelar envio", cancel_document_path, :confirm => 'Você tem certeza?', :method => :put %> |
  <%= link_to "Ver todos", documents_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :all %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <header>
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <% end %>
        <nav>
          <% if user_signed_in? %>
            <ul>
              <li><%= link_to "Editar perfil", edit_user_registration_path %></li>
              <li><%= link_to "Sair", destroy_user_session_path, :method => :delete %></li>
            </ul>
          <% end %>
        </nav>
      </header>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>